from typing import Dict, List

from tools.registry import registry


class ToolExecutor:
    """
    Executes the tool calls generated by the orchestrator.
    """

    def execute(self, plan: Dict) -> List[Dict]:
        outputs = []

        for step in plan.get("tools", []):

            tool_name = step["tool"]
            query = step.get("query", "")

            try:
                tool = registry.get(tool_name)

                result = tool.run(query)

                outputs.append(result)

            except Exception as e:
                outputs.append({
                    "tool": tool_name,
                    "query": query,
                    "error": str(e)
                })

        return outputs


executor = ToolExecutor()